sergey-koryshev/idler

- src/Idler/MainWindow.xaml
- src/Idler/MainWindow.xaml.cs
- src/Idler/Properties/AssemblyInfo.cs
- main window contains `MainWindow` in title. We need to change it to follow: `<Application Name> (<Major Version>.<Minor Version>)
- filled out version in `AssemblyInfo.cs`
- implemented logic to display application name and version in main window's title
> [feature] change caption of main window

- src/Idler/About.xaml
- src/Idler/About.xaml.cs
- src/Idler/Idler.csproj
- src/Idler/MainWindow.xaml
- src/Idler/MainWindow.xaml.cs
- need to implement menu `Help`. It should contain two items: `Content` and `About`. `Content` should lead to GitHub related page and `About` should open window with information about the application
- added new window `About` which shows follow information
- name and version of the application
- description of the application
- author's name
- link to application's GitHub page: `https://github.com/sergey-koryshev/Idler`
- introduced new menu group `Help`. It contains follow items:
- `Content` - opens page `https://github.com/sergey-koryshev/Idler/tree/release/poc` in browser
- `About` - opens window `About`
> [feature] Implement menu "Help"

- src/Idler/SettingsWindow.xaml
- user cannot save new path to source because of property is changed only when field lost focus
- name of table with note categories are wrong
- set `UpdateSourceTrigger` to `PropertyChanged` in binging for Source and Data Provider fields
- changed name of note categories table
Issue: #15, #14
> [bug] User cannot specify different path to data base file

- src/Idler/Commands/AddNoteCommand.cs
- src/Idler/MainWindow.xaml.cs
- src/Idler/Properties/AssemblyInfo.cs
- src/Idler/ViewModels/AddNoteViewModel.cs
- need to refactor view model `AddNoteViewModel` since it's recreated every time when shift is changed and all information are cleared in the view model
- implemented logic to update properties `Shift` and `NoteCategories` instead of creating new view model every time when shift is changed
- removed unused code
> Refactor AddNoteViewModel

- src/Idler/Properties/AssemblyInfo.cs
- src/Idler/Shift.cs
- `Total Effort` counter is not updated when a note is deleted due to UI is not notified about fact of deleting the note
- implemented logic to notify UI about changing note collection
> Total Effort is not updated when a note is deleted

- src/Idler/MainWindow.xaml.cs
- src/Idler/Properties/AssemblyInfo.cs
- `Total Effort` counter doesn't equal to `0` because of missed logic to recalculate the property when new shift is created
- rise event `PropertyChanged` when new shift is created
> Idler shows non-zero total effort for new shift

- src/Idler/Properties/AssemblyInfo.cs
- src/Idler/ViewModels/AddNoteViewModel.cs
- src/Idler/Views/AddNoteView.xaml
- spellcheck language is not changed when user changes input language
- implemented logic to set language which is used in spellcheck when user changes input language
> Spellcheck doesn't work properly during note creation

- .github/workflows/dev-build.yml
Dev-build is not started by `Create Version Label` due to incorrect name of workflow
> Correct name of workflow which triggers dev-build

- src/Idler/Commands/AddNoteCommand.cs
- src/Idler/MainWindow.xaml.cs
- src/Idler/Shift.cs
Reminder's timer ignores recently created notes and display notification despite the fact that user created some note a moment ago. This happens due to we don't have a logic to reset the timer when new note is added
- moved logic related to reminder to `Shift` class to get access to it from `AddNoteCommand`
- added method `ResetReminder` to reset the timer
> [bug] Reminders ignore recently created notes

- src/Idler/MainWindow.xaml.cs
- src/Idler/NoteCategories.cs
- src/Idler/ViewModels/AddNoteViewModel.cs
Changing `hidden` attribute of categories is not reflected in creating note drop box because of missed logic to refresh the drop box view when only properties of categories are changed.
Implemented logic to refresh the drop box view after each updating of `NoteCategories` class
> [bug] Categories are not updated in the list when user changes their visibility

- src/Idler/Views/AddNoteView.xaml
- src/Idler/Views/ListNotesView.xaml
If name of category is longer than width of drop down then part of name is hidden, need to implement tooltip to be able to see full name of it
- implemented tooltip for both category drop downs: in note and add note views
- implemented ellipsis if name is longer than width of drop down
> [bug] Can't see full name of category

- src/Idler/Views/ListNotesView.xaml
Remove button disappears when mouse is between description input and the button because of the fact that margin between description input and the button doesn't trigger `MouseOver` event
Added transparent background to the parent `StackPanel` so it fixes issue with `MouseOver` event for margins
> [Bug] Remove button sometimes disappears even when mouse over note row

- src/Idler/Commands/AddNoteCommand.cs
- src/Idler/Converters/DoubleConverter.cs
- src/Idler/Idler.csproj
- src/Idler/MainWindow.xaml.cs
- src/Idler/ViewModels/AddNoteViewModel.cs
- src/Idler/Views/AddNoteView.xaml
- src/Idler/Views/ListNotesView.xaml
Dot cannot be typed in effort input within list notes due to binding issues. Since number cannot end with `.` sign (because it cannot be casted to `decimal` type), standard behaviour of `TextBox` doesn't allow the sign in the end of number.
The issue could be fixed by changing `UpdateSourceTrigger` to `LostFocus` but it would bring regression to user experience. So I implemented `DoubleConverter` to manage a process of parsing entering number. Except fixing the issue, it also bring new feature: now the input can take both decimal symbols `.` and `,`, and parse entering number to decimal value correctly. 
Related issue: #56
> [bug] Dot cannot be typed in effort input

- src/Idler/Commands/RefreshNotesCommand.cs
- src/Idler/Components/PopupDialogControl/Buttons.cs
- src/Idler/Components/PopupDialogControl/Commands.cs
- src/Idler/Components/PopupDialogControl/PopupDialog.cs
- src/Idler/Components/PopupDialogControl/Result.cs
- src/Idler/Components/PopupDialogControl/Style.xaml
- src/Idler/Components/PopupDialogHostControl/PopupDialogHost.cs
- src/Idler/Components/PopupDialogHostControl/Style.xaml
- src/Idler/Idler.csproj
- src/Idler/MainWindow.xaml
- src/Idler/MainWindow.xaml.cs
- src/Idler/Themes/Generic.xaml
Button `Refresh` must give ability to reset changes but it becomes inactive when user makes changes. Need to remove logic to disable the button and introduce confirmation dialog if there are unsaved changes
- implemented new custom components
- `PopupDialog` - represents popup dialog which takes 3 parameters: `Title`, `Message` and `Buttons`
- `PopupDialogHost` - container to show popup dialog within. It contains method `ShowDialog` which creates new `PopupDialog` with provided parameters and put it inside `PopupDialogHost` component. Waiting for pressing buttons in dialogs was implemented via small hack to "freeze" thread. Need to keep in mind that potentially it can harm performance
- implemented `PopupDialogHost` in main window
- added command to refresh notes to show confirmation …
> Button "Refresh" must be active to give ability to reset changes

- src/Idler/Views/ListNotesView.xaml
Notes related text boxes lost sharpness when they are not blurred due to the fact that when `Radius` of `BlurEffect` equals to `0` then it seems still blurred despite zero-value. I didn't found information related this so probably it can be considered as WPF related bug
I fixed it by removing `BlurEffect` for not blurred elements. It works as expected but as far as I understand if we decide to implement some animation for blur action we will have some problems with such approach
> Notes lost sharpness

- src/Idler/About.xaml.cs
- src/Idler/MainWindow.xaml.cs
Need to remove version from Main Window's title
- removed version from Main Window's title
- make window `About` show all 4 numbers of version
- changed copyright line
> Remove version from main window title

- src/Idler/App.xaml
- src/Idler/Helpers/MVVM/ObservableObject.cs
- src/Idler/MainWindow.xaml.cs
- src/Idler/NoteCategories.cs
- src/Idler/NoteCategory.cs
- src/Idler/SettingsWindow.xaml
- src/Idler/SettingsWindow.xaml.cs
- src/Idler/ShiftNote.cs
- src/Idler/ViewModels/AddNoteViewModel.cs
- src/Idler/ViewModels/ListNotesViewModel.cs
Buttons `Save` and `Reset` are active always but they need to be active only if user made some changes there
- implemented logic to enable buttons only if there are changes in settings/notes
- fixed bug when category disappears from list notes and dropdown in adding note area if user click button `Reset`. The issue occurs due to strange behaviour of `ComboBox` component. I had to implement logic to send addition event `PropertyChange` on each `CategoryId` to fix binding.
- removed odd binding errors for `ComboBox` by setting properties `HorizontalContentAlignment` and `VerticalContentAlignment` explicitly in `App.xaml`
> Button Save on Settings window must be activated only if there are changes in settings

- src/Idler/Shift.cs
If user sets date manually then duplicated notes are loaded. This happens because data picker element fires property changed event two times: by `DatePicker` and by `Calendar`.
I added check if there is ongoing refresh task and jus skip refreshing in this case.
> If user set date manually then duplicated notes are displayed

- src/Idler/MainWindow.xaml.cs
Need to show confirmation popup before closing the app if there are unsaved changes
implemented showing confirmation popup in two places:
- when user closes main window
- when user clicks on menu item `File -> Exit`
> Implement confirmation before closing the app

- src/Idler/App.config
- src/Idler/MainWindow.xaml
- src/Idler/MainWindow.xaml.cs
- src/Idler/Properties/Settings.Designer.cs
- src/Idler/Properties/Settings.settings
Need to make the app save position and size of main window and restore it when user launch the app again
1. added new settings:
- MainWindowHeight
- MainWindowWidth
- MainWindowLeft
- MainWindowTop
- MainWindowMaximized
2. implemented logic to save size and position of main window before closing it
3. implemented logic to restore size and position of main window before its initialization
> Save position and size of main window and restore it after app restart

- README.md
- src/Idler/App.config
- src/Idler/Converters/TotalEffortToColorConverter.cs
- src/Idler/Extensions/ColorExtensions.cs
- src/Idler/Extensions/CommonExtensions.cs
- src/Idler/Helpers/DB/DataBaseFunctions.cs
- src/Idler/Idler.csproj
- src/Idler/MainWindow.xaml
- src/Idler/MainWindow.xaml.cs
- src/Idler/Models/DarkerColorAttribute.cs
- src/Idler/Models/TotalEffortType.cs
- src/Idler/Properties/Settings.Designer.cs
- src/Idler/Properties/Settings.settings
- src/Idler/SettingsWindow.xaml
- added new settings:
- DailyWorkLoad - work load for one day
- IsOvertimeHighlighted - enables highlighting of overtimes
- IsHighlightingEnabled - enables highlighting of work days
- applied style for day button in calendar components which uses converter `TotalEffortToColorConverter` to convert total effort to color
- added DB function to get total effort for every day in specified month
> Highligh dates if there are notes in date picker
